homeworld: Lamia
primal:
  - Behemoth
  - Excalibur
  - Exodus
  - Famfrit
  - Hyperion
  - Lamia
  - Leviathan
  - Ultros

gemstoneItems:
  - id: 44064
    name: Swampmonk Thigh
    area: Kozama'uka
    cost: 3
  - id: 44054
    name: Hammerhead Crocodile Skin
    area: Kozama'uka
    cost: 3
  - id: 44068
    name: Poison Frog Secretions
    area: Kozama'uka
    cost: 3
  - id: 44069
    name: Lesser Apollyon Shell
    area: Kozama'uka
    cost: 3
  - id: 44063
    name: Alpaca Fillet
    area: Urqopacha
    cost: 3
  - id: 44067
    name: Megamaguey Pineapple
    area: Urqopacha
    cost: 3
  - id: 44053
    name: Silver Lobo Hide
    area: Urqopacha
    cost: 3
  - id: 44055
    name: Br'aax Hide
    area: Yak T'el
    cost: 3
  - id: 44065
    name: Branchbearer Fruit
    area: Yak T'el
    cost: 3
  - id: 44070
    name: Ty'aitya Wingblade
    area: Yak T'el
    cost: 3
  - id: 44066
    name: Nopalitender Tuna
    area: Shaaloani
    cost: 3
  - id: 44106
    name: Rroneek Chuck
    area: Shaaloani
    cost: 3
  - id: 44027
    name: Rroneek Fleece
    area: Shaaloani
    cost: 3
  - id: 44071
    name: Tumbleclaw Weeds
    area: Shaaloani
    cost: 3
  - id: 44056
    name: Gomphotherium Skin
    area: Heritage Found
    cost: 3
  - id: 44072
    name: Axe Beak Wing
    area: Heritage Found
    cost: 3
  - id: 44057
    name: Gargantua Hide
    area: Living Memory
    cost: 3

flip:
  dropdownOptions:
    - Raid Consumables
    - Crafting Mats
    - Crafting Gear
    - Materia
  itemLists:
    consumables:
      - 44162
      - 44163
      - 44165
      - 44166
      - 44177
      - 44175
      - 44176
      - 44178
    craftingMats:
      - 37282
      - 36116
    craftingGear:
      - 38891
      - 38892
      - 38893
      - 38894
      - 38895
    materia:
      - 41772
      - 41759
      - 41773
      - 41760
      - 41769
      - 41782
      - 41776
      - 41775
      - 41779
      - 41780
      - 41778

pricechecker:
  default:
    - 44143
    - 44144
    - 44145
    - 44146
    - 44141
    - 44142
