defaultWorld: Lamia
primal:
  - Behemoth
  - Excalibur
  - Exodus
  - Famfrit
  - Hyperion
  - Lamia
  - Leviathan
  - Ultros

flip:
  dropdownOptions:
    - Raid Consumables
    - Crafting Mats
    - Crafting Gear
    - Materia
  itemLists:
    consumables:
      - 39727
      - 39728
      - 39730
      - 39731
      - 39872
      - 39876
    craftingMats:
      - 37282
      - 36116
    craftingGear:
      - 38891
      - 38892
      - 38893
      - 38894
      - 38895
    materia:
      - 33919
      - 33932
      - 33918
      - 33931
      - 33920
      - 33933
      - 33929
      - 33942
      - 33928
      - 33941
